### ISSUE TITLE
New contributions

### ISSUE THREAD

**Issue by AnSiChen** [raestrada/storycraftr#1]
Hello, I like this repo and I would like to know if you guys are still actively accepting contributions. I have a couple of ideas for the project, including but not limited to restructuration, translation, and new features. Thank you!

**Comment by raestrada** [comment]
Hello! Yes, we are actively accepting contributions—it's exactly what we're hoping for. Please follow the [contribution guide](https://github.com/raestrada/storycraftr/blob/main/CONTRIBUTING.md) to get started.

A couple of things to keep in mind:
- The tests are currently not updated and may not be fully functional.
- We do require the pre-commit git hook to be run (you can set this up by running `pre-commit install`) before we accept any pull requests, as the PR checks will validate that it has been executed.
- We use **Black** to maintain consistent code formatting across the project.

Thanks for your interest and ideas, and we look forward to your contributions!
